/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.SistemGudang.program;

import java.awt.HeadlessException;
import java.sql.SQLException;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author USER
 */
public class Gudang extends javax.swing.JFrame {
    public void kosongkanTblGudang(){
        txtKode_Gudang.setEditable(true);
        txtKode_Gudang.setText(null);
        txtPenyimpanan.setSelectedItem(null);
        txtNama_Gudang.setText(null);
        txtKapasitas.setText(null);
        txtLuas.setText(null);        
    }
    
    private void tampilkanDataGudang(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Gudang");
        model.addColumn("Jenis Gudang");
        model.addColumn("Nama");
        model.addColumn("Kapasitas");
        model.addColumn("Luas");
        
        try{
            String sql = "SELECT * FROM gudang";
            java.sql.Connection conn = (Connection)Konfig.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),
                                          res.getString(2),
                                          res.getString(3),
                                          res.getString(4),
                                          res.getString(5),
                                         });
            }
            tabelGudang.setModel(model);
            
        }catch (SQLException e){
            System.out.println("Error : " + e.getMessage());
        }
    }
    
     
    /** Creates new form Gudang */
    public Gudang() {
        initComponents();
        tampilkanDataGudang();        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbTambah_Gudang = new javax.swing.JButton();
        tbKembali_Gudang = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tbUpdate_Gudang = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tbHapus_Gudang = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelGudang = new javax.swing.JTable();
        txtNama_Gudang = new javax.swing.JTextField();
        txtLuas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKapasitas = new javax.swing.JTextField();
        txtPenyimpanan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtKode_Gudang = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbTambah_Gudang.setText("Tambah Data");
        tbTambah_Gudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTambah_GudangActionPerformed(evt);
            }
        });
        getContentPane().add(tbTambah_Gudang, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        tbKembali_Gudang.setText("Kembali");
        tbKembali_Gudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbKembali_GudangActionPerformed(evt);
            }
        });
        getContentPane().add(tbKembali_Gudang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel5.setText("Jenis Penyimpanan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Data Gudang");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        tbUpdate_Gudang.setText("Update");
        tbUpdate_Gudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbUpdate_GudangActionPerformed(evt);
            }
        });
        getContentPane().add(tbUpdate_Gudang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        tbHapus_Gudang.setText("Hapus");
        tbHapus_Gudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHapus_GudangActionPerformed(evt);
            }
        });
        getContentPane().add(tbHapus_Gudang, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        jLabel4.setText("Luas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        tabelGudang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelGudang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelGudangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelGudang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 430, 100));

        txtNama_Gudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNama_GudangActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama_Gudang, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 182, -1));
        getContentPane().add(txtLuas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 182, -1));

        jLabel3.setText("Kapasitas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));
        getContentPane().add(txtKapasitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 182, -1));

        txtPenyimpanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Barang" }));
        txtPenyimpanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPenyimpananActionPerformed(evt);
            }
        });
        getContentPane().add(txtPenyimpanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        jLabel6.setText("Kode Gudang");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        txtKode_Gudang.setText("33");
        txtKode_Gudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKode_GudangActionPerformed(evt);
            }
        });
        getContentPane().add(txtKode_Gudang, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbTambah_GudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTambah_GudangActionPerformed
        // TODO add your handling code here:
        
        DataGudang x = new DataGudang();
        x.setData(txtKode_Gudang.getText(), txtNama_Gudang.getText(), txtPenyimpanan.getSelectedItem().toString() , txtKapasitas.getText(), txtLuas.getText());
        //jika data yang diinputkan sesuai dengan kriteria
        //maka akan dilakukan penginputan data pada database
        if(x.isStatus()==0){
            //mencoba terhubung dengan database
            try{
                int reply = JOptionPane.showConfirmDialog(null, "Simpan Data Gudang ?");
                if(reply == JOptionPane.YES_OPTION){
                    //Query Penambahan data pada Database
                    String sql = "INSERT INTO gudang VALUES ('"+x.getKode()+"','"+x.getJenis()+"','"+x.getNama()+"','"+x.getKapasitas()+"','"+x.getLuas()+"')";
                    java.sql.Connection conn = (Connection)Konfig.configDB();
                    java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                    pstm.execute();
                    kosongkanTblGudang();
                    tampilkanDataGudang();
                }else if(reply == JOptionPane.NO_OPTION){
                    kosongkanTblGudang();
                }
                //jika tidak terhubung dengan database
            }catch(HeadlessException | SQLException e){
                //JOptionPane.showMessageDialog(this, e.getMessage());
                JOptionPane.showMessageDialog(this, "Kode Gudang sudah terdaftar \nSilahkan masukkan Kode lain");
                
            }
        }else if(x.isStatus()==1){
            JOptionPane.showMessageDialog(null, "Kode Gudang dimulai dengan kode 33 dan berjumlah 5 angka \n\n Example : 33001");
            txtKode_Gudang.setText(null);
        }else if(x.isStatus()==2){
            JOptionPane.showMessageDialog(null, "Terdapat angka pada pengisian Nama Gudang");
            txtNama_Gudang.setText(null);
        }else if(x.isStatus()==3){
            JOptionPane.showMessageDialog(null, "Terdapat huruf pada pengisian Kapasitas Gudang ");
            txtKapasitas.setText(null);
        }else if(x.isStatus()==4){
            JOptionPane.showMessageDialog(null, "Terdapat huruf pada pengisian Luas Gudang ");
            txtLuas.setText(null);
        }else if(x.isStatus()==5){
            JOptionPane.showMessageDialog(null, "Terdapat huruf pada pengisian Kode Gudang ");
            txtKode_Gudang.setText(null);
        }
    }//GEN-LAST:event_tbTambah_GudangActionPerformed

    private void tbUpdate_GudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbUpdate_GudangActionPerformed
        // TODO add your handling code here:

        DataGudang x = new DataGudang();
        x.setData(txtKode_Gudang.getText(), txtNama_Gudang.getText(), txtPenyimpanan.getSelectedItem().toString() , txtKapasitas.getText(), txtLuas.getText());
        if(x.isStatus()==0){
            try{                     
                //Query Update database
                String sql = "UPDATE gudang SET Kode_Gudang = "+x.getKode()+",Nama_Gudang = '"+x.getNama()+"',Jenis_Penyimpanan = '"+x.getJenis()+"',Kapasitas ='"+x.getKapasitas()+"',Luas_Gudang = '"+x.getLuas()+"'WHERE Kode_Gudang = '"+txtKode_Gudang.getText()+"'" ;
                java.sql.Connection conn = (Connection)Konfig.configDB();
                java.sql.PreparedStatement pstm = conn.prepareCall(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null,"Berhasil Mengubah Data");
                kosongkanTblGudang();
                tampilkanDataGudang();
            }catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
                //JOptionPane.showMessageDialog(this,"Kode Gudang Tidak ditemukan");
                //txtKode_Gudang.setText(null);
            }
        }else if(x.isStatus()==1){
            JOptionPane.showMessageDialog(null, "Kode Gudang dimulai dengan kode 33 dan berjumlah 5 angka \n\n Example : 33001");
            txtKode_Gudang.setText(null);
        }else if(x.isStatus()==2){
            JOptionPane.showMessageDialog(null, "Terdapat angka pada pengisian Nama Gudang");
            txtNama_Gudang.setText(null);
        }else if(x.isStatus()==3){
            JOptionPane.showMessageDialog(null, "Terdapat huruf pada pengisian Kapasitas Gudang ");
            txtKapasitas.setText(null);
        }else if(x.isStatus()==4){
            JOptionPane.showMessageDialog(null, "Terdapat huruf pada pengisian Luas Gudang ");
            txtLuas.setText(null);
        }else if(x.isStatus()==5){
            JOptionPane.showMessageDialog(null, "Terdapat huruf pada pengisian Kode Gudang ");
            txtKode_Gudang.setText(null);
        }
    }//GEN-LAST:event_tbUpdate_GudangActionPerformed

    private void tbHapus_GudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHapus_GudangActionPerformed
        // TODO add your handling code here:
        try{
            int reply = JOptionPane.showConfirmDialog(null, "apakah anda yakin untuk menghapus data ?");
            if(reply == JOptionPane.YES_OPTION){
                String sql = "DELETE FROM gudang WHERE Kode_gudang = '"+txtKode_Gudang.getText()+"'";
                java.sql.Connection conn = (Connection)Konfig.configDB();
                java.sql.PreparedStatement pstm = conn.prepareCall(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null,"Berhasil Menghapus Data");
                kosongkanTblGudang();
                tampilkanDataGudang();
            }else if(reply == JOptionPane.NO_OPTION){
                kosongkanTblGudang();
            }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showConfirmDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_tbHapus_GudangActionPerformed

    private void tabelGudangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelGudangMouseClicked
        // TODO add your handling code here:
        int baris = tabelGudang.rowAtPoint(evt.getPoint());
        
        String kode = tabelGudang.getValueAt(baris,0).toString();
        txtKode_Gudang.setText(kode);
                
        String  penyimpanan= tabelGudang.getValueAt(baris,1).toString();
        txtPenyimpanan.setSelectedItem(penyimpanan);
        
        String  nama= tabelGudang.getValueAt(baris,2).toString();
        txtNama_Gudang.setText(nama);

        String  kapasitas= tabelGudang.getValueAt(baris,3).toString();
        txtKapasitas.setText(kapasitas);

        String  Luas= tabelGudang.getValueAt(baris,4).toString();
        txtLuas.setText(Luas);
    }//GEN-LAST:event_tabelGudangMouseClicked

    private void txtNama_GudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNama_GudangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNama_GudangActionPerformed

    private void txtPenyimpananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPenyimpananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPenyimpananActionPerformed

    private void tbKembali_GudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbKembali_GudangActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tbKembali_GudangActionPerformed

    private void txtKode_GudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKode_GudangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKode_GudangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gudang().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabelGudang;
    private javax.swing.JButton tbHapus_Gudang;
    private javax.swing.JButton tbKembali_Gudang;
    private javax.swing.JButton tbTambah_Gudang;
    private javax.swing.JButton tbUpdate_Gudang;
    private javax.swing.JTextField txtKapasitas;
    private javax.swing.JTextField txtKode_Gudang;
    private javax.swing.JTextField txtLuas;
    private javax.swing.JTextField txtNama_Gudang;
    private javax.swing.JComboBox<String> txtPenyimpanan;
    // End of variables declaration//GEN-END:variables

}
