/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.SistemGudang.program;

/**
 *
 * @author USER
 */
public class Home extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        LabelHome = new javax.swing.JLabel();
        tbExitHome = new javax.swing.JButton();
        tbSupplier = new javax.swing.JToggleButton();
        tbKaryawan = new javax.swing.JToggleButton();
        tbBarang = new javax.swing.JToggleButton();
        tbBarang_Masuk = new javax.swing.JButton();
        tbBarang_Keluar = new javax.swing.JToggleButton();
        tbGudang = new javax.swing.JButton();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelHome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelHome.setText("HOME");

        tbExitHome.setText("Exit");
        tbExitHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbExitHomeActionPerformed(evt);
            }
        });

        tbSupplier.setText("Data Supplier");
        tbSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSupplierActionPerformed(evt);
            }
        });

        tbKaryawan.setText("Data Karyawan");
        tbKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbKaryawanActionPerformed(evt);
            }
        });

        tbBarang.setText("Data Barang");
        tbBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbBarangActionPerformed(evt);
            }
        });

        tbBarang_Masuk.setText("Barang Masuk");
        tbBarang_Masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbBarang_MasukActionPerformed(evt);
            }
        });

        tbBarang_Keluar.setText("Barang Keluar");
        tbBarang_Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbBarang_KeluarActionPerformed(evt);
            }
        });

        tbGudang.setText("Data Gudang");
        tbGudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbGudangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(LabelHome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tbKaryawan)
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tbGudang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tbSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))))))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbBarang_Masuk)
                    .addComponent(tbBarang_Keluar))
                .addGap(80, 80, 80)
                .addComponent(tbExitHome, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(LabelHome)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbBarang)
                    .addComponent(tbGudang))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbKaryawan)
                    .addComponent(tbSupplier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tbExitHome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tbBarang_Masuk)
                        .addGap(17, 17, 17)
                        .addComponent(tbBarang_Keluar)
                        .addGap(43, 43, 43))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbExitHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbExitHomeActionPerformed
        System.exit(0);
// TODO add your handling code here:
    }//GEN-LAST:event_tbExitHomeActionPerformed

    private void tbBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbBarangActionPerformed
        // TODO add your handling code here:
        new Barang().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tbBarangActionPerformed

    private void tbKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbKaryawanActionPerformed
        // TODO add your handling code here:
        new Karyawan().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tbKaryawanActionPerformed

    private void tbSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSupplierActionPerformed
        // TODO add your handling code here:
        new Supplier().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tbSupplierActionPerformed

    private void tbBarang_MasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbBarang_MasukActionPerformed
        // TODO add your handling code here:
        new InputBarang().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tbBarang_MasukActionPerformed

    private void tbBarang_KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbBarang_KeluarActionPerformed
        // TODO add your handling code here:
        new OutputBarang().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tbBarang_KeluarActionPerformed

    private void tbGudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbGudangActionPerformed
        // TODO add your handling code here:
        new Gudang().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tbGudangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelHome;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JToggleButton tbBarang;
    private javax.swing.JToggleButton tbBarang_Keluar;
    private javax.swing.JButton tbBarang_Masuk;
    private javax.swing.JButton tbExitHome;
    private javax.swing.JButton tbGudang;
    private javax.swing.JToggleButton tbKaryawan;
    private javax.swing.JToggleButton tbSupplier;
    // End of variables declaration//GEN-END:variables
}
