/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.SistemGudang.program;

import java.awt.HeadlessException;
import java.sql.SQLException;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import com.SistemGudang.program.editStok;
import com.SistemGudang.program.editKapasitas;

/**
 *
 * @author USER
 */
public class InputBarang extends javax.swing.JFrame {
    //Proses mengkosongkan tampilan tabel
    public void kosongkanTblInput(){
            txtKode.setEditable(true);
            txtKode.setText(null);
            tbNama.setSelectedItem(this);
            txtJumlah.setText(null);
            tbID.setSelectedItem(this);
        }
    
    //Proses mengeluarkan data pada tabel Input_barang
    private void tampilkanDataInput(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode input");
        model.addColumn("Tanggal");
        model.addColumn("Nama Barang");
        model.addColumn("Jumlah");
        model.addColumn("ID Supplier");
        
        try{
            String sql = "SELECT * FROM input_barang";
            java.sql.Connection conn = (Connection)Konfig.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),
                                          res.getString(2),
                                          res.getString(3),
                                          res.getString(4),
                                          res.getString(5),       
                                         });
            }
            tabelInput.setModel(model);
            
        }catch (SQLException e){
            System.out.println("Error : " + e.getMessage());
        }
    }
    
    //Proses menampilkan DropDown dari Nama Barang yang sudah ada di Gudang
    public void tampilkanNama()
    {   
        try
        {   
            String sql = "select nama_barang from barang";
            java.sql.Connection conn = (Connection)Konfig.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while(res.next())
            {
                tbNama.addItem(res.getString("Nama_Barang"));
            }
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }
    
    //Proses menampilkan DropDown dari ID Supplier yang sudah ada
    public void tampilkanID()
    {   
        try
        {   
            String sql = "select ID_supplier from supplier";
            java.sql.Connection conn = (Connection)Konfig.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while(res.next())
            {
                tbID.addItem(res.getString("ID_Supplier"));
            }
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());            
        }
    }
    
    /**
     * Creates new form InputBarang
     */
    public InputBarang() {
        initComponents();
        kosongkanTblInput();
        tampilkanDataInput();
        tampilkanNama();
        tampilkanID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbTambah_Input = new javax.swing.JButton();
        tbKembali_Input = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tbHapus_Input = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelInput = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tbID = new javax.swing.JComboBox<>();
        tbNama = new javax.swing.JComboBox<>();
        txtDate = new com.toedter.calendar.JDateChooser();
        txtJumlah = new javax.swing.JTextField();
        txtKode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbTambah_Input.setText("Tambah Data");
        tbTambah_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTambah_InputActionPerformed(evt);
            }
        });
        getContentPane().add(tbTambah_Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        tbKembali_Input.setText("Kembali");
        tbKembali_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbKembali_InputActionPerformed(evt);
            }
        });
        getContentPane().add(tbKembali_Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 212, -1, -1));

        jLabel5.setText("Tanggal Input");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 78, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Form Input Barang");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 11, -1, -1));

        jLabel2.setText("Jumlah");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        tbHapus_Input.setText("Hapus");
        tbHapus_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHapus_InputActionPerformed(evt);
            }
        });
        getContentPane().add(tbHapus_Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 212, -1, -1));

        jLabel4.setText("ID Supplier");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 172, -1, -1));

        tabelInput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelInputMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelInput);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 242, 430, 100));

        jLabel3.setText("Nama Barang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel6.setText("Kode Input");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 51, -1, -1));

        tbID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih ID Supplier -" }));
        getContentPane().add(tbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 169, 160, -1));

        tbNama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Nama Barang -" }));
        getContentPane().add(tbNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 160, -1));

        txtDate.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 160, 30));
        getContentPane().add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 160, -1));

        txtKode.setText("44");
        getContentPane().add(txtKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 48, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbTambah_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTambah_InputActionPerformed
        // TODO add your handling code here:
        
        String tampilan ="yyyy-MM-dd" ; 
        SimpleDateFormat fm = new SimpleDateFormat(tampilan); 
        String tanggal = String.valueOf(fm.format(txtDate.getDate()));
        
        DataInputBarang x = new DataInputBarang();
        x.setData(txtKode.getText(), tanggal, tbNama.getSelectedItem().toString() , txtJumlah.getText(), tbID.getSelectedItem().toString());
        //jika data yang diinputkan sesuai dengan kriteria
        //maka akan dilakukan penginputan data pada database
        if(x.isStatus()==0){
            //mencoba terhubung dengan database da
            try{
                int reply = JOptionPane.showConfirmDialog(null, "Tambahkan "+txtJumlah.getText()+" barang ?");
                if(reply == JOptionPane.YES_OPTION){
                    //Query Penambahan data pada Database
                    String sql = "INSERT INTO Input_Barang VALUES ('"+x.getKodeInput()+"','"+x.getTanggal()+"','"+x.getNama()+"','"+x.getJumlah()+"','"+x.getID()+"')";
                    java.sql.Connection conn = (Connection)Konfig.configDB();
                    java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                    pstm.execute();
                    
                    //Proses Penambahan Stok pada barang yang baru masuk
        
                    editStok A = new editStok(tbNama.getSelectedItem().toString(),tabelInput);
                    //Proses menentukan nilai Stok Baru
                    int  jumlahUpdate= Integer.parseInt(tabelInput.getValueAt(0, 0).toString()) + Integer.parseInt(txtJumlah.getText());
                    //JOptionPane.showConfirmDialog(null, Integer.toString(jumlahUpdate));
                    //Mengganti nilai stok pada barang dan mencari Kode Gudang
                    A.Query(tbNama.getSelectedItem().toString(), jumlahUpdate,tabelInput);

                    //Pengurangan Kapasitas pada tabel Gudang
                    String Kode =tabelInput.getValueAt(0, 0).toString();
                    //dapet kode gudang
                    editKapasitas B = new editKapasitas(tabelInput.getValueAt(0, 0).toString() , tabelInput);
                    //dapet kapasitas
                    jumlahUpdate = Integer.parseInt(tabelInput.getValueAt(0, 0).toString()) - Integer.parseInt(txtJumlah.getText());
                    B.Query(Kode, jumlahUpdate);
                    
                    kosongkanTblInput();
                    tampilkanDataInput();
                }else if(reply == JOptionPane.NO_OPTION){
                    kosongkanTblInput();
                }
            //jika tidak terhubung dengan database 
            //atau terdapat masalah pada proses berinteraksi dengan database
            }catch(HeadlessException | SQLException e){
                //JOptionPane.showMessageDialog(this, e.getMessage());
                JOptionPane.showMessageDialog(this, "Kode Gudang sudah terdaftar \nSilahkan masukkan Kode lain");

            }
        }else if(x.isStatus()== 1 ){
            JOptionPane.showMessageDialog(null, "Terdapat Huruf pada pengisian Kode Input ");
            txtKode.setText(null);
        }else if(x.isStatus()==2){
            JOptionPane.showMessageDialog(null, "Kode Input dimulai dengan kode 44 dan berjumlah 5 angka \n\n Example : 44009");
            txtKode.setText(null);
        }else if(x.isStatus()==3){
            JOptionPane.showMessageDialog(null, "Silahkan pilih Tanggal Input");
            txtDate.setDate(null);
        }else if(x.isStatus()==4){
            JOptionPane.showMessageDialog(null, "Silahkan pilih nama barang ");
            tbNama.setSelectedItem(this);
        }else if(x.isStatus()==5){
            JOptionPane.showMessageDialog(null, "Terdapat huruf pada pengisian Jumlah");
            txtJumlah.setText(null);
        }else if(x.isStatus()==6){
            JOptionPane.showMessageDialog(null, "Silahkan pilih ID Supplier");
            tbID.setSelectedItem(this);
        }
    }//GEN-LAST:event_tbTambah_InputActionPerformed

    private void tbHapus_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHapus_InputActionPerformed
        // TODO add your handling code here:
        
        try{
            int reply = JOptionPane.showConfirmDialog(null, " Jika anda menghapus data, Stok barang akan berkurang \n apakah anda yakin untuk menghapus data ?");
            if(reply == JOptionPane.YES_OPTION){
                String sql = "DELETE FROM Input_Barang WHERE Kode_Penginputan = '"+txtKode.getText()+"'";
                java.sql.Connection conn = (Connection)Konfig.configDB();
                java.sql.PreparedStatement pstm = conn.prepareCall(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null,"Berhasil Menghapus Data");
                
                 //Proses Pengurangan Stok pada barang yang tidak jadi dimasukkan
                editStok A = new editStok(tbNama.getSelectedItem().toString(),tabelInput);
                int  jumlahUpdate= Integer.parseInt(tabelInput.getValueAt(0, 0).toString()) - Integer.parseInt(txtJumlah.getText());
                A.Query(tbNama.getSelectedItem().toString(), jumlahUpdate,tabelInput);

                //Penambahan Kapasitas pada tabel Gudang dikarenakan barang berkurang
                String Kode =tabelInput.getValueAt(0, 0).toString();
                editKapasitas B = new editKapasitas(tabelInput.getValueAt(0, 0).toString() , tabelInput);
                jumlahUpdate = Integer.parseInt(tabelInput.getValueAt(0, 0).toString()) + Integer.parseInt(txtJumlah.getText());
                B.Query(Kode, jumlahUpdate);
                
                kosongkanTblInput();
                tampilkanDataInput();
            }else if(reply == JOptionPane.NO_OPTION){
                kosongkanTblInput();
            }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_tbHapus_InputActionPerformed

    private void tabelInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelInputMouseClicked
        // TODO add your handling code here:
        int baris = tabelInput.rowAtPoint(evt.getPoint());

        String kode = tabelInput.getValueAt(baris,0).toString();
        txtKode.setText(kode);

        String  date= tabelInput.getValueAt(baris,1).toString();
        txtDate.setDateFormatString(date);

        String  nama= tabelInput.getValueAt(baris,2).toString();
        tbNama.setSelectedItem(nama);

        String  Jumlah= tabelInput.getValueAt(baris,3).toString();
        txtJumlah.setText(Jumlah);

        String  ID= tabelInput.getValueAt(baris,4).toString();
        tbID.setSelectedItem(ID);
    }//GEN-LAST:event_tabelInputMouseClicked

    private void tbKembali_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbKembali_InputActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_tbKembali_InputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabelInput;
    public javax.swing.JButton tbHapus_Input;
    public javax.swing.JComboBox<String> tbID;
    public javax.swing.JButton tbKembali_Input;
    public javax.swing.JComboBox<String> tbNama;
    public javax.swing.JButton tbTambah_Input;
    public com.toedter.calendar.JDateChooser txtDate;
    public javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKode;
    // End of variables declaration//GEN-END:variables

  
}
