/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.SistemGudang.program;

import java.awt.HeadlessException;
import java.sql.SQLException;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Karyawan extends javax.swing.JFrame {    
    
    public void kosongkanTblKaryawan(){
        txtID_Karyawan.setEditable(true);
        txtID_Karyawan.setText(null);
        txtNama_Karyawan.setText(null);
        txtGender_Karyawan.setSelectedItem(this);
        txtNoHp_Karyawan.setText(null);
        txtAlamat_Karyawan.setText(null);
        txtJabatan_Karyawan.setSelectedItem(this);
    }
    
    private void tampilkanDataKaryawan(){
        //pembuatan tabel sesuai dengan data yang akan ditampilkan
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Gender");
        model.addColumn("No HP");
        model.addColumn("Alamat");
        model.addColumn("Jabatan");
        
        try{
            String sql = "SELECT * FROM karyawan";
            java.sql.Connection conn = (Connection)Konfig.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            //penelusuran seluruh data pada table didalam database
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),
                                          res.getString(2),
                                          res.getString(3),
                                          res.getString(4),
                                          res.getString(5),
                                          res.getString(6),
                                         });
            }
            tabelKaryawan.setModel(model);
        }catch (SQLException e){
            System.out.println("Error : " + e.getMessage());
        }
    }
    
    /**
     * Creates new form Karyawan
     */
    public Karyawan() {
        initComponents();
        tampilkanDataKaryawan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNama_Karyawan = new javax.swing.JTextField();
        txtNoHp_Karyawan = new javax.swing.JTextField();
        txtAlamat_Karyawan = new javax.swing.JTextField();
        tbTambah_Karyawan = new javax.swing.JButton();
        tbKembali_Karyawan = new javax.swing.JButton();
        txtGender_Karyawan = new javax.swing.JComboBox<>();
        txtID_Karyawan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tbUpdate_Karyawan = new javax.swing.JButton();
        tbHapus_Karyawan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKaryawan = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtJabatan_Karyawan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Sistem Gudang");
        setName("saa\n"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Data Karyawan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel3.setText("Jenis Kelamin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, 20));

        jLabel4.setText("Nomor HP");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        txtNama_Karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNama_KaryawanActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama_Karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 144, -1));
        getContentPane().add(txtNoHp_Karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 144, -1));
        getContentPane().add(txtAlamat_Karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 144, -1));

        tbTambah_Karyawan.setText("Tambah Data");
        tbTambah_Karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTambah_KaryawanActionPerformed(evt);
            }
        });
        getContentPane().add(tbTambah_Karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        tbKembali_Karyawan.setText("Kembali");
        tbKembali_Karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbKembali_KaryawanActionPerformed(evt);
            }
        });
        getContentPane().add(tbKembali_Karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txtGender_Karyawan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pria", "Wanita" }));
        getContentPane().add(txtGender_Karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        txtID_Karyawan.setText("11");
        getContentPane().add(txtID_Karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 140, -1));

        jLabel5.setText("ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        tbUpdate_Karyawan.setText("Update");
        tbUpdate_Karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbUpdate_KaryawanActionPerformed(evt);
            }
        });
        getContentPane().add(tbUpdate_Karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        tbHapus_Karyawan.setText("Hapus");
        tbHapus_Karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHapus_KaryawanActionPerformed(evt);
            }
        });
        getContentPane().add(tbHapus_Karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        tabelKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelKaryawan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 100));

        jLabel7.setText("Jabatan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        txtJabatan_Karyawan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sekretasi", "Bendahara", "Sales", "Audit", "Marketing" }));
        getContentPane().add(txtJabatan_Karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        setBounds(0, 0, 502, 416);
    }// </editor-fold>//GEN-END:initComponents

    private void tbTambah_KaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTambah_KaryawanActionPerformed
        // TODO add your handling code here:
        
        DataKaryawan x = new DataKaryawan();
        x.setData(txtID_Karyawan.getText() , txtNama_Karyawan.getText(), txtNoHp_Karyawan.getText(), txtAlamat_Karyawan.getText());
        x.setGender(txtGender_Karyawan.getSelectedItem().toString());
        x.setJabatan(txtJabatan_Karyawan.getSelectedItem().toString());
        
        //jika data yang diinputkan sesuai dengan kriteria
        //maka akan dilakukan penginputan data pada database
        if(x.isStatus()==0){
            //mencoba terhubung dengan database
            try{
                int reply = JOptionPane.showConfirmDialog(null, "Simpan Data Karyawan ?");
                if(reply == JOptionPane.YES_OPTION){
                    String sql = "INSERT INTO karyawan VALUES ('"+Integer.toString(x.getID())+"','"+x.getNama()+"','"+x.getGender()+"','"+x.getNo_Hp()+"','"+x.getAlamat()+"','"+x.getJabatan()+"')";
                    java.sql.Connection conn = (Connection)Konfig.configDB();
                    java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                    pstm.execute();
                    kosongkanTblKaryawan();
                    tampilkanDataKaryawan();
                }else if(reply == JOptionPane.NO_OPTION){
                    kosongkanTblKaryawan();
                }
            //jika terdapat kendala
            }catch(HeadlessException | SQLException e){
                //JOptionPane.showMessageDialog(this, e.getMessage());
                //namun karena kendala yang biasanya muncul adalah penambahan ID yang sama
                JOptionPane.showMessageDialog(this, "ID Supplier sudah tersedia \nSilahkan masukkan ID lain");
            }            
        }
        //jika data yang diinputkan tida sesuai kriteria
        //maka akan diberikan notice sesuai kesalahan penginputan
        else if(x.isStatus()==4){
            JOptionPane.showMessageDialog(null, "Nomor Hp harus berisi 11 sampai 13 angka");
            txtNoHp_Karyawan.setText(null);
        }else if(x.isStatus()==3){
            JOptionPane.showMessageDialog(null, "Terdapat huruf pada pengisian nomor Hp");
            txtNoHp_Karyawan.setText(null);
        }else if(x.isStatus()==2){
            JOptionPane.showMessageDialog(null, "Terdapat angka pada pengisian Nama ");
            txtNama_Karyawan.setText(null);
        }else if(x.isStatus()==1){
            JOptionPane.showMessageDialog(null, "Terdapat huruf pada pengisian ID ");
            txtID_Karyawan.setText(null);
        }else if(x.isStatus()==5){
            JOptionPane.showMessageDialog(null, "ID Karyawan dimulai dengan kode 11 dan berjumlah 5 angka \n\n Example : 11002");
            txtID_Karyawan.setText(null);
        }
    }//GEN-LAST:event_tbTambah_KaryawanActionPerformed

    private void txtNama_KaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNama_KaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNama_KaryawanActionPerformed

    
    private void tabelKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKaryawanMouseClicked
        // TODO add your handling code here:
        int baris = tabelKaryawan.rowAtPoint(evt.getPoint());
        
        String ID = tabelKaryawan.getValueAt(baris,0).toString();
        txtID_Karyawan.setText(ID);
        
        String  nama= tabelKaryawan.getValueAt(baris,1).toString();
        txtNama_Karyawan.setText(nama);
        
        String  gender= tabelKaryawan.getValueAt(baris,2).toString();
        txtGender_Karyawan.setSelectedItem(gender);
        
        String  no= tabelKaryawan.getValueAt(baris,3).toString();
        txtNoHp_Karyawan.setText(no);
        
        String  alamat= tabelKaryawan.getValueAt(baris,4).toString();
        txtAlamat_Karyawan.setText(alamat);
        
        String Jabatan = tabelKaryawan.getValueAt(baris, 5).toString();
        txtJabatan_Karyawan.setSelectedItem(Jabatan);
    }//GEN-LAST:event_tabelKaryawanMouseClicked

    private void tbUpdate_KaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbUpdate_KaryawanActionPerformed
        // TODO add your handling code here:
        
        DataKaryawan x = new DataKaryawan();
        x.setData(txtID_Karyawan.getText() , txtNama_Karyawan.getText(), txtNoHp_Karyawan.getText(), txtAlamat_Karyawan.getText());
        x.setGender(txtGender_Karyawan.getSelectedItem().toString());
        x.setJabatan(txtJabatan_Karyawan.getSelectedItem().toString());
        if(x.isStatus()==0){
            try{                     
                //Query Update database
                String sql = "UPDATE karyawan SET ID_Karyawan = '"+Integer.toString(x.getID())+"',Nama_Karyawan = '"+x.getNama()+"',NoHp_Karyawan ='"+x.getNo_Hp()+"',Alamat_Karyawan = '"+x.getAlamat()+"',jabatan = '"+x.getJabatan()+"' WHERE ID_Karyawan = '"+txtID_Karyawan.getText()+"'" ;
                java.sql.Connection conn = (Connection)Konfig.configDB();
                java.sql.PreparedStatement pstm = conn.prepareCall(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null,"Berhasil Mengubah Data");
                kosongkanTblKaryawan();
                tampilkanDataKaryawan();                
            }catch(HeadlessException | SQLException e){
                JOptionPane.showConfirmDialog(this, e.getMessage());
                JOptionPane.showMessageDialog(this,"ID Karyawan Tidak ditemukan");
            }
        }else if(x.isStatus()==4){
            JOptionPane.showMessageDialog(null, "Nomor Hp harus berisi 11 sampai 13 angka");
            txtNoHp_Karyawan.setText(null);
        }else if(x.isStatus()==3){
            JOptionPane.showMessageDialog(null, "Terdapat huruf pada pengisian nomor Hp");
            txtNoHp_Karyawan.setText(null);
        }else if(x.isStatus()==2){
            JOptionPane.showMessageDialog(null, "Terdapat angka pada pengisian Nama ");
            txtNama_Karyawan.setText(null);
        }else if(x.isStatus()==1){
            JOptionPane.showMessageDialog(null, "Terdapat huruf pada pengisian ID ");
            txtID_Karyawan.setText(null);
    }//GEN-LAST:event_tbUpdate_KaryawanActionPerformed
}
    private void tbHapus_KaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHapus_KaryawanActionPerformed
        // TODO add your handling code here:
        try{
            int reply = JOptionPane.showConfirmDialog(null, "apakah anda yakin untuk menghapus data ?");
            if(reply == JOptionPane.YES_OPTION){
                String sql = "DELETE FROM Karyawan WHERE ID_Karyawan = '"+txtID_Karyawan.getText()+"'";
                java.sql.Connection conn = (Connection)Konfig.configDB();
                java.sql.PreparedStatement pstm = conn.prepareCall(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null,"Berhasil Menghapus Data");
                kosongkanTblKaryawan();
                tampilkanDataKaryawan();
            }else if(reply == JOptionPane.NO_OPTION){
                kosongkanTblKaryawan();
            }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showConfirmDialog(this, e.getMessage());
        }      
    }//GEN-LAST:event_tbHapus_KaryawanActionPerformed

    private void tbKembali_KaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbKembali_KaryawanActionPerformed
        // TODO add your handling code here:
        
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tbKembali_KaryawanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabelKaryawan;
    private javax.swing.JButton tbHapus_Karyawan;
    private javax.swing.JButton tbKembali_Karyawan;
    private javax.swing.JButton tbTambah_Karyawan;
    private javax.swing.JButton tbUpdate_Karyawan;
    private javax.swing.JTextField txtAlamat_Karyawan;
    private javax.swing.JComboBox<String> txtGender_Karyawan;
    private javax.swing.JTextField txtID_Karyawan;
    private javax.swing.JComboBox<String> txtJabatan_Karyawan;
    private javax.swing.JTextField txtNama_Karyawan;
    private javax.swing.JTextField txtNoHp_Karyawan;
    // End of variables declaration//GEN-END:variables
}
