/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.SistemGudang.program;

import java.awt.HeadlessException;
import java.sql.SQLException;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author USER
 */
public class Supplier extends javax.swing.JFrame {
    public void kosongkanTblSupplier(){
        txtID_Supplier.setEditable(true);
        txtID_Supplier.setText(null);
        txtNama_Supplier.setText(null);
        txtNoHp_Supplier.setText(null);
        txtPerusahaan.setText(null);
        txtAlamat_Supplier.setText(null);
    }
    
    private void tampilkanDataSupplier(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("No HP");
        model.addColumn("Perusahaan");
        model.addColumn("Alamat");
        
        try{
            String sql = "SELECT * FROM supplier";
            java.sql.Connection conn = (Connection)Konfig.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),
                                          res.getString(2),
                                          res.getString(3),
                                          res.getString(4),
                                          res.getString(5),       
                                         });
            }
            tabelSupplier.setModel(model);
            
        }catch (SQLException e){
            System.out.println("Error : " + e.getMessage());
        }
    }
    
    /* Creates new form Supplier
     */
    public Supplier() {
        initComponents();
        tampilkanDataSupplier();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNama_Supplier = new javax.swing.JTextField();
        txtNoHp_Supplier = new javax.swing.JTextField();
        txtAlamat_Supplier = new javax.swing.JTextField();
        tbTambah_Supplier = new javax.swing.JButton();
        tbKembali_Supplier = new javax.swing.JButton();
        txtID_Supplier = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tbUpdate_Supplier = new javax.swing.JButton();
        tbHapus_Supplier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSupplier = new javax.swing.JTable();
        txtPerusahaan = new javax.swing.JTextField();
        txtNama_Perusahaan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Data Supplier");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 0, -1, -1));

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 85, -1, -1));

        jLabel4.setText("Nomor HP");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 115, -1, -1));

        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 177, -1, -1));

        txtNama_Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNama_SupplierActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama_Supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 82, 150, -1));
        getContentPane().add(txtNoHp_Supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 112, 150, -1));

        txtAlamat_Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamat_SupplierActionPerformed(evt);
            }
        });
        getContentPane().add(txtAlamat_Supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 174, 150, -1));

        tbTambah_Supplier.setText("Tambah Data");
        tbTambah_Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTambah_SupplierActionPerformed(evt);
            }
        });
        getContentPane().add(tbTambah_Supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 212, -1, -1));

        tbKembali_Supplier.setText("Kembali");
        tbKembali_Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbKembali_SupplierActionPerformed(evt);
            }
        });
        getContentPane().add(tbKembali_Supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 212, -1, -1));

        txtID_Supplier.setText("22");
        getContentPane().add(txtID_Supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 52, 150, -1));

        jLabel5.setText("ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 55, -1, -1));

        tbUpdate_Supplier.setText("Update");
        tbUpdate_Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbUpdate_SupplierActionPerformed(evt);
            }
        });
        getContentPane().add(tbUpdate_Supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 212, -1, -1));

        tbHapus_Supplier.setText("Hapus");
        tbHapus_Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHapus_SupplierActionPerformed(evt);
            }
        });
        getContentPane().add(tbHapus_Supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 212, -1, -1));

        tabelSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelSupplier);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 242, 433, 111));

        txtPerusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerusahaanActionPerformed(evt);
            }
        });
        getContentPane().add(txtPerusahaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 143, 150, -1));

        txtNama_Perusahaan.setText("Nama Perusahaan");
        getContentPane().add(txtNama_Perusahaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 146, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNama_SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNama_SupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNama_SupplierActionPerformed

    private void tbTambah_SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTambah_SupplierActionPerformed
        // TODO add your handling code here:

        DataSupplier x = new DataSupplier();
        x.setData(txtID_Supplier.getText() , txtNama_Supplier.getText(), txtNoHp_Supplier.getText(),txtPerusahaan.getText(), txtAlamat_Supplier.getText());
        //jika data yang diinputkan sesuai dengan kriteria
        //maka akan dilakukan penginputan data pada database
        if(x.isStatus()==0){
            //mencoba terhubung dengan database
            try{
                int reply = JOptionPane.showConfirmDialog(null, "Simpan Data Supplier ?");
                if(reply == JOptionPane.YES_OPTION){
                    String sql = "INSERT INTO supplier VALUES ('"+Integer.toString(x.getID())+"','"+x.getNama()+"','"+x.getNo_Hp()+"','"+x.getNamaPerusahaan()+"','"+x.getAlamat()+"')";
                    java.sql.Connection conn = (Connection)Konfig.configDB();
                    java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                    pstm.execute();
                    kosongkanTblSupplier();
                    tampilkanDataSupplier();
                }else if(reply == JOptionPane.NO_OPTION){
                    kosongkanTblSupplier();
                }
                //jika tidak terhubung dengan database
            }catch(HeadlessException | SQLException e){
                //JOptionPane.showMessageDialog(this, e.getMessage());
                JOptionPane.showMessageDialog(this, "ID Supplier sudah tersedia \nSilahkan masukkan ID lain");
            }
        }else if(x.isStatus()==4){
            JOptionPane.showMessageDialog(null, "Nomor Hp harus berisi 11 sampai 13 angka");
            txtNoHp_Supplier.setText(null);
        }else if(x.isStatus()==3){
            JOptionPane.showMessageDialog(null, "Terdapat huruf pada pengisian nomor Hp");
            txtNoHp_Supplier.setText(null);
        }else if(x.isStatus()==2){
            JOptionPane.showMessageDialog(null, "Terdapat angka pada pengisian Nama ");
            txtNama_Supplier.setText(null);
        }else if(x.isStatus()==1){
            JOptionPane.showMessageDialog(null, "Terdapat huruf pada pengisian ID ");
            txtID_Supplier.setText(null);
        }else if(x.isStatus()==5){
            JOptionPane.showMessageDialog(null, "ID Supplier dimulai dengan kode 22 dan berjumlah 5 angka \n\n Example : 22003");
            txtID_Supplier.setText(null);
        }
    }//GEN-LAST:event_tbTambah_SupplierActionPerformed

    private void tbUpdate_SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbUpdate_SupplierActionPerformed
        // TODO add your handling code here:

        DataSupplier x = new DataSupplier();
        x.setData(txtID_Supplier.getText() , txtNama_Supplier.getText(), txtNoHp_Supplier.getText(),txtPerusahaan.getText(), txtAlamat_Supplier.getText());
        if(x.isStatus()==0){
            try{  
                //Query Update database
                String sql = "UPDATE supplier SET ID_Supplier = '"+Integer.toString(x.getID())+"',Nama_Supplier = '"+x.getNama()+"',NoHp_Supplier ='"+x.getNo_Hp()+"',Alamat_Supplier = '"+x.getAlamat()+"',Perusahaan = '"+x.getNamaPerusahaan()+"'WHERE ID_Supplier = '"+txtID_Supplier.getText()+"'" ;
                java.sql.Connection conn = (Connection)Konfig.configDB();
                java.sql.PreparedStatement pstm = conn.prepareCall(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null,"Berhasil Mengubah Data");
                kosongkanTblSupplier();
                tampilkanDataSupplier();
            }catch(HeadlessException | SQLException e){
                //JOptionPane.showConfirmDialog(this, e.getMessage());
                JOptionPane.showMessageDialog(this,"ID Supplier Tidak ditemukan");
            }            
        }else if(x.isStatus()==4){
            JOptionPane.showMessageDialog(null, "Nomor Hp harus berisi 11 sampai 13 angka");
            txtNoHp_Supplier.setText(null);
        }else if(x.isStatus()==3){
            JOptionPane.showMessageDialog(null, "Terdapat huruf pada pengisian nomor Hp");
            txtNoHp_Supplier.setText(null);
        }else if(x.isStatus()==2){
            JOptionPane.showMessageDialog(null, "Terdapat angka pada pengisian Nama ");
            txtNama_Supplier.setText(null);
        }else if(x.isStatus()==1){
            JOptionPane.showMessageDialog(null, "Terdapat huruf pada pengisian ID ");
            txtID_Supplier.setText(null);
        }else if(x.isStatus()==5){
            JOptionPane.showMessageDialog(null, "ID Supplier dimulai dengan kode 22 dan berjumlah 5 angka \n\n Example : 22003");
            txtID_Supplier.setText(null);
        }
        
    }//GEN-LAST:event_tbUpdate_SupplierActionPerformed

    
    private void tbHapus_SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHapus_SupplierActionPerformed
        // TODO add your handling code here:
        try{
            int reply = JOptionPane.showConfirmDialog(null, "apakah anda yakin untuk menghapus data ?");
            if(reply == JOptionPane.YES_OPTION){
                String sql = "DELETE FROM supplier WHERE ID_Supplier = '"+txtID_Supplier.getText()+"'";
                java.sql.Connection conn = (Connection)Konfig.configDB();
                java.sql.PreparedStatement pstm = conn.prepareCall(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null,"Berhasil Menghapus Data");
                kosongkanTblSupplier();
                tampilkanDataSupplier();
            }else if(reply == JOptionPane.NO_OPTION){
                kosongkanTblSupplier();
            }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showConfirmDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_tbHapus_SupplierActionPerformed

    private void tabelSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelSupplierMouseClicked
        // TODO add your handling code here:
        int baris = tabelSupplier.rowAtPoint(evt.getPoint());

        String ID = tabelSupplier.getValueAt(baris,0).toString();
        txtID_Supplier.setText(ID);

        String  nama= tabelSupplier.getValueAt(baris,1).toString();
        txtNama_Supplier.setText(nama);

        String  no= tabelSupplier.getValueAt(baris,2).toString();
        txtNoHp_Supplier.setText(no);
        
        String perusahaan= tabelSupplier.getValueAt(baris,3).toString();
        txtPerusahaan.setText(perusahaan);
        
        String  alamat= tabelSupplier.getValueAt(baris,4).toString();
        txtAlamat_Supplier.setText(alamat);
    }//GEN-LAST:event_tabelSupplierMouseClicked

    private void txtAlamat_SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamat_SupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamat_SupplierActionPerformed

    private void txtPerusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerusahaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerusahaanActionPerformed

    private void tbKembali_SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbKembali_SupplierActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_tbKembali_SupplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabelSupplier;
    private javax.swing.JButton tbHapus_Supplier;
    private javax.swing.JButton tbKembali_Supplier;
    private javax.swing.JButton tbTambah_Supplier;
    private javax.swing.JButton tbUpdate_Supplier;
    private javax.swing.JTextField txtAlamat_Supplier;
    private javax.swing.JTextField txtID_Supplier;
    private javax.swing.JLabel txtNama_Perusahaan;
    private javax.swing.JTextField txtNama_Supplier;
    private javax.swing.JTextField txtNoHp_Supplier;
    private javax.swing.JTextField txtPerusahaan;
    // End of variables declaration//GEN-END:variables
}
